// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjxhtsvuybtureddgswk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqeGh0c3Z1eWJ0dXJlZGRnc3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODg1ODYsImV4cCI6MjA2NDQ2NDU4Nn0.9VNF3EmabXA4CU-VJDWDokJnWxUVrMXsk0pqd0Ee9Fk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);